package lab_1.MyBatis.Model;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.ID
     *
     * @mbg.generated Tue Apr 28 15:25:19 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.FULL_NAME
     *
     * @mbg.generated Tue Apr 28 15:25:19 EEST 2020
     */
    private String fullName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.HOTEL_ID
     *
     * @mbg.generated Tue Apr 28 15:25:19 EEST 2020
     */
    private Integer hotelId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE.ID
     *
     * @return the value of PUBLIC.EMPLOYEE.ID
     *
     * @mbg.generated Tue Apr 28 15:25:19 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE.ID
     *
     * @param id the value for PUBLIC.EMPLOYEE.ID
     *
     * @mbg.generated Tue Apr 28 15:25:19 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE.FULL_NAME
     *
     * @return the value of PUBLIC.EMPLOYEE.FULL_NAME
     *
     * @mbg.generated Tue Apr 28 15:25:19 EEST 2020
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE.FULL_NAME
     *
     * @param fullName the value for PUBLIC.EMPLOYEE.FULL_NAME
     *
     * @mbg.generated Tue Apr 28 15:25:19 EEST 2020
     */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE.HOTEL_ID
     *
     * @return the value of PUBLIC.EMPLOYEE.HOTEL_ID
     *
     * @mbg.generated Tue Apr 28 15:25:19 EEST 2020
     */
    public Integer getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE.HOTEL_ID
     *
     * @param hotelId the value for PUBLIC.EMPLOYEE.HOTEL_ID
     *
     * @mbg.generated Tue Apr 28 15:25:19 EEST 2020
     */
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }
}