package lab_1.MyBatis.Model;

public class Guest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GUEST.ID
     *
     * @mbg.generated Tue Apr 28 15:25:19 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GUEST.NAME
     *
     * @mbg.generated Tue Apr 28 15:25:19 EEST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GUEST.ID
     *
     * @return the value of PUBLIC.GUEST.ID
     *
     * @mbg.generated Tue Apr 28 15:25:19 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GUEST.ID
     *
     * @param id the value for PUBLIC.GUEST.ID
     *
     * @mbg.generated Tue Apr 28 15:25:19 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GUEST.NAME
     *
     * @return the value of PUBLIC.GUEST.NAME
     *
     * @mbg.generated Tue Apr 28 15:25:19 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GUEST.NAME
     *
     * @param name the value for PUBLIC.GUEST.NAME
     *
     * @mbg.generated Tue Apr 28 15:25:19 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }
}