package lab_1.MyBatis.dao;

import java.util.List;
import lab_1.MyBatis.Model.Hotel;
import org.mybatis.cdi.Mapper;

@Mapper
public interface HotelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.HOTEL
     *
     * @mbg.generated Tue Apr 28 15:25:19 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.HOTEL
     *
     * @mbg.generated Tue Apr 28 15:25:19 EEST 2020
     */
    int insert(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.HOTEL
     *
     * @mbg.generated Tue Apr 28 15:25:19 EEST 2020
     */
    Hotel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.HOTEL
     *
     * @mbg.generated Tue Apr 28 15:25:19 EEST 2020
     */
    List<Hotel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.HOTEL
     *
     * @mbg.generated Tue Apr 28 15:25:19 EEST 2020
     */
    int updateByPrimaryKey(Hotel record);
}